### ISSUE TITLE
Browser should not render server state

### ISSUE THREAD

**Issue by Kroonax** [damian-pastorini/reldens#38]
Hello there, I posted on HTML5GameDevs but my post is awaiting confirmation, so I'm just going to post it here instead :

I understand the server authority in terms of movements and action, but shouldn't it follow the "typical" MMORPG model ?

Wouldn't it be more fluid to "lag compensate" after server verification, instead of taking in all the inputs, processing them, then returning the result on the client-side ?

On a typical online game, the client renders what is called a "temporary state" which is right inbetween the client state and the server state : This state allows the client to experience no input lag, it is a far better user experience ! For example, if the player is pressing key thats fires a spell after a cast time of 1.5sec , the cast bar would be directly displayed (instant feedback), but he cast would be finally delayed for (cast time + latency), making it 1.6 or 1.7sec in the end, but without the frustration of having the latency between the keypress and the network transit.

If the movement was click based I wouldn't mind, but the way this is intended to be played (movement buttons and key presses) makes it really frustrating; And I can't imagine your model doing well with 50+ CCU, more users means more latency overall, and at some point having so much input lag will make it unplayable (and I mean no offence at all).

I didn't really take the time to explore the entirety of your code, but I think you should just replicate the inputs on the client side and verify that they are valid afterwards.

This will force you to also replicate a client-side map in order to check events (collisions, NPC events, etc.) on the client. The server will still have authority, for example, battle checks (damages, etc.) will only be done server-side, but for player movement and UI interactions, the browser should not render the server state or everything can become extremely laggy if the user has a mediocre internet access or if there are a lot of players connected.

EDIT : Oh, and also, amazing work ! I am digging the project ! Expect me to give you a hand on it soon :)

**Comment by Kroonax** [comment]
Ok, my bad on this one, it might be a "smoothing" issue.

Browser is indeed not rendering server-state, but a mix of both, but not the "temporary" state we want. The fact that the rollback (server check) is instantaneous blocks or delays user inputs and gives a weird feedback.

Shouldn't it be smoother (or less frustrating at least) to force kind of a "tickrate" for the server checks and validations emits ?

**Comment by damian-pastorini** [comment]
Hi @Kroonax ,

Firs of all thanks for you imput! I really appreciate it!

I'll split my reply in some items to be clear :)

1 - I think HTML5devs forum (where I've posted about the project originally) is closed, or at least they've moved the Phaser 3 forums to https://phaser.discourse.group/c/showcase, so I'm not sure if your post is going to be published, you can try to reply on my original post though (https://www.html5gamedevs.com/topic/40120-base-mmorpg-node-mysql-colyseus-parcel-and-phaser-3/) but as you did better here :)

2 - What you are talking about here is "client-prediction", as you commented this will be when the client starts an action (let's say animations or movement), even before the server returns the "real position", and then it gets validated with the server return working as authority to fix the position (if needed). 
Though is a feature I would love to have at some point, it is something really complex to implement (maybe because in my research I didn't find a node game server with any of that implemented, the best I've found was Colyseus, which in my opinion is amazing but it doesn't have any client-prediction by default), and though client-prediction helps on the user experience it doesn't help that much.
Why I'm saying this? 
First, because you can only use it for certain and let's say "public" data, for example movement, but you can't have data about "private actions" like hidden objects or any like that on the client side, and you could even get a worst user experience if you use it for let's say bullets which may run into an early "hit" animation (because you are also trying to replicate collisions on client) when actually, because of your client lag, the bullet never had hit the target.
Second, because it only makes the experience a bit smooth but if you have really lag issues it won't help you at all (lag is lag, you will need to improve other stuff to fix it). If you have 50+ CCU you may need to improve your infrastructure or how your implementation handle maps and so. For example use smaller maps and limit the sync between the users "in view" instead on have a huge map with a lot of users to keep in sync.
To summarize, the way I see it now, implement client prediction will take me too much time for just some minimal lag compensation, so it's in my road map but for now really in the future.

3 - From your second comment > "Browser is indeed not rendering server-state, but a mix of both" > just to clarify: the way this platform works is by using the server as full authority, this is to avoid any kind of hacks on the client side (can't trust client data at all).
For this matter and to improve communications or how to scale your implementation you can check how Colyseus works since we are not modifying anything related to the communications, remember we are just integrating and adding features in a implementation based on other platforms (Colyseus for communications and Phaser just for client side animations).

That said, I would like to mention that the last work done is not on the master branch but on: 
https://github.com/damian-pastorini/reldens/tree/v4.0.0-npm-setup-v1
Which is the branch that contains the project version that will be pushed on NPM.

Hope this reply to your doubts, you can join me on Discord if you like https://discord.gg/HuJMxUY
Best,

**Comment by Kroonax** [comment]
For the client prediction, I found an interesting source (a little old, but the logic flow is basically the same) : https://alankydd.wordpress.com/2017/07/31/client-side-prediction-and-server-reconciliation-with-node-js-socket-io-phaser/

About the server authority, I'm with you, but like 99%. In order to have the best user experience possible, it's common to have some server replication on the client, for example I think this is logical to have the map replicated on the client, with all the entities.

This will make it way more smooth with collisions, NPC interactions, etc...

Server-side you would just have to check the conditions in order to trigger an event with an NPC (ex: distance), a teleporter, etc...

If the client cheats (ex: speedhack) you could define a value on the server that is a reference to a "legit" range of velocity, if the client goes too fast, you just roll it back with the server-side reconciliation. The cheater will just rubberband into oblivion :)

As long as your server logic is rock-solid, I don't think it matters much if the client edits values because they will be rejected by the server.

**Comment by damian-pastorini** [comment]
Yeah, there a lot of examples, here's another interesting link about with a really cool live demo:
https://www.gabrielgambetta.com/client-side-prediction-live-demo.html
But as I was saying is not that easier to implement at all.
Obviously you will be welcome to contribute to the project if you manage to make it work 😄

**Comment by damian-pastorini** [comment]
I'm closing this since it's not actually an issue, is been always in the the road map: 
https://github.com/damian-pastorini/reldens/wiki/Road-Map
😄
